### PR TITLE
Add Metro North Vehicle Positions extension for statuses

### PR DESCRIPTION
**Pull request by sdjacobs**
This PR adds a MNR GTFS-RT extension which adds "DELAYED" as a vehicle status.

### CODE REVIEW

**Comment by barbeau** [comment]
So this is an extension for a direct field within VehiclePosition, right?

Like:

~~~
vehicle {
    ...
    current_status: DELAYED
}
~~~

Shouldn't it have a default value that's not `DELAYED`, though?

**Comment by sdjacobs** [comment]
I think you just wouldn't set anything in the current_status field in that case, since it's optional.

Note it isn't a direct extension to the status field, it's part of an extension to VehiclePosition -- e.g. `VehiclePosition.mnr_vehicle_position.current_status`.

**Comment by sdjacobs** [comment]
Put another way:

```
vehicle {
    ...
    mnr_vehicle_position {
        current_status: DELAYED
    }
}
```

**Comment by barbeau** [comment]
>I think you just wouldn't set anything in the current_status field in that case, since it's optional.

Unfortunately protobufs (at least proto2, which I'm most familiar with) don't have a concept of "no value".

From https://developers.google.com/protocol-buffers/docs/proto#optional:

>As mentioned above, elements in a message description can be labeled optional. A well-formed message may or may not contain an optional element. When a message is parsed, if it does not contain an optional element, the corresponding field in the parsed object is set to the default value for that field. The default value can be specified as part of the message description....
>...
>If the default value is not specified for an optional element, a type-specific default value is used instead...For enums, the default value is the first value listed in the enum's type definition.

So, given the last sentence if you don't have an `UNKNOWN` enum value and have that as the default, then the default value for each position will be `DELAYED`.

**Comment by sdjacobs** [comment]
Wow, I didn't realize that! That's super surprising to me... surprising enough that I wrote some tests.
 
If you don't set a value in `current_status`, it reports that field as empty. But, it will return `DELAYED` if you ask for the value anyway: https://github.com/sdjacobs/onebusaway-gtfs-realtime-api/blob/f7cdb142b15378db05eb1ddb8b30a6c0353680b0/src/test/java/com/google/transit/realtime/MnrVehiclePositionTest.java#L46-L57

In my opinion, if you ignore the result of `hasCurrentStatus()` and then call `getCurrentStatus()` anyway, you're asking for a perverse result!

That said, if there's consensus that this extension is using protobuf in an incorrect way, we'll rework this with the MTA developer we've been working with.

**Comment by barbeau** [comment]
Thanks for the tests! Yes, it's a bizarre quirk of protobufs. It gets even worse when you consider that the .proto stub compiler is under no obligation to create the "hasX()" functions - at least Java is nice enough to do that. But the. NET

**Pull request closed without merging**
