### PR TITLE
Use protobuf-maven-plugin to compile extensions automatically

### PR DESCRIPTION
**Pull request by kurtraschke**
This PR (which is built on top of #16) adds [`protobuf-maven-plugin`](https://www.xolstice.org/protobuf-maven-plugin/) to automatically invoke `protoc` as part of the build process (using a build of `protoc` which is packaged as a Maven artifact so it is not required to be installed locally).

In the future it would be nice to find some good way to get the canonical `gtfs-realtime.proto` into this repository automatically (or, perhaps, include it as a Maven dependency).

The brute-force solution to this would be to fetch `https://raw.githubusercontent.com/google/transit/master/gtfs-realtime/proto/gtfs-realtime.proto` as part of the build process (for example, with the Maven AntRun plugin), but it doesn't really matter much anyway, as the only updates to `gtfs-realtime.proto` that would matter in this context would be entirely new entities (and even then only if we wanted to extend them).

### CODE REVIEW

**Comment by barbeau** [comment]
Closing and re-opening, which should hopefully trigger Travis...

**Comment by barbeau** [comment]
@kurtraschke Sorry, I edited the README which caused conflicts with your changes. Would you mind resolving that (for some reason I can't via GitHub UI)?

**Comment by leonardehrenfried** [comment]
I'm quite interested in this change and wonder if it's possible to merge in.

In particular, I'd like to add the following change to the library and this PR would simplify adding it: https://github.com/google/transit/commit/5ce5f0400c349eaf25cb250d4c49bbeb81af7a9a

**Comment by sheldonabrown** [comment]
Sorry all, I'm still working with some projects using protoc 2.5 and protoc 2.6, so I've been hesitant to merge this.  Perhaps I simply should branch for those to keep the project alive.  Let me add another reminder...

**Review by sheldonabrown — APPROVED** [review]
Thanks Kurt!

**Pull request merged**
