### PR TITLE
Switch upstream dependency to io.mobilitydata.transit:gtfs-realtime-bindings:0.0.5

### PR DESCRIPTION
**Pull request by kurtraschke**
This PR bumps the upstream dependency to `io.mobilitydata.transit:gtfs-realtime-bindings:0.0.5`.

Unfortunately there's a bit of churn along with it because this also bumps the transitive dependency on the Java protobuf runtime from 2.6.1 to 3.6.1, which necessitates re-running `protoc` on the extensions, but the current version of `protoc` is 3.11.4, so we end up having to pull in that version of the protobuf runtime as an explicit dependency instead.

### CODE REVIEW

**Comment by barbeau** [comment]
I'm a +1 for this change (io.mobilitydata.transit is the new canonical home for gtfs-realtime-bindings, and I'm the primary maintainer there).

@sheldonabrown Looks like you've been doing work recently on this project. I'd merge, but I don't want to interfere/break your changes. Would you be able to review?

**Comment by kurtraschke** [comment]
> Unfortunately, it looks like we don't have any unit tests here...

I've just opened #18 to add a rudimentary round-trip test which exercises some of the extensions in this repository.

**Comment by barbeau** [comment]
Closing and re-opening, which should hopefully trigger Travis...

**Review by sheldonabrown — APPROVED** [review]
Looks good to me.  I'm going to accept this even though some of the bindings have changed, as later commits help with the bindings.

**Pull request merged**
